### ISSUE TITLE
Reports of pre-release successes or failures for 7.5.0

### ISSUE THREAD

**Issue by mwcraig** [BruceSherwood/vpython-jupyter#124]
If you have tried out 7.5.0beta1 please let us know whether or not it worked for you here by adding a comment below.

**Comment by BruceSherwood** [comment]
I've executed nearly all the standard demos in spyder 3.3.3 running in Python 3.7. scene.capture('mypic') now works. winput sets up an input box into which I can type, but pressing Enter doesn't do anything, so I need to correct something in vpython.py and/or the comm file(s). I note the Python 3.7 warning about clock: "DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead". Amusingly, we already import "clock" in both GlowScript VPython and VPython 7 when you say "from vpython import *", so for this usage case I can just swing "clock" to point to a new time element, and existing programs won't be affected by Python's change.

**Comment by BruceSherwood** [comment]
I was wrong about winput. It is working as advertised. I finished running all the demo programs in Python 3.7 with Spyder 3.3.3. And as intended, Matt has succeeded in making it possible to run a VPython program without any graphics, just print statements, with no browser tab opening.  I also ran a couple programs in IDLE, no problem.

**Comment by BruceSherwood** [comment]
I've now run all the standard demos in jupyter notebook and in jupyter lab. No problems.

**Comment by BruceSherwood** [comment]
I should have stated that my checking was done on Windows 10.

**Comment by mwcraig** [comment]
Excellent!

**Comment by mwcraig** [comment]
Closing, since 7.5.0 was just released
