### ISSUE TITLE
Make the `Launch Binder` badge point at the beta site

### ISSUE THREAD

**Issue by fomightez** [BruceSherwood/vpython-jupyter#30]
I think if you just change the link in the badge to `http://beta.mybinder.org/repo/BruceSherwood/vpython-jupyter` it will work again. (see https://groups.google.com/d/msg/vpython-users/S7s81g4TVRw/kQ8Ky1RWCAAJ where I touched on why I am not just issuing a PR of my fork.) 
Of course, that is until they change the beta to be the current version.

**Comment by mwcraig** [comment]
Thanks for opening this, @fomightez
