### ISSUE TITLE
Support for Jupyter Lab

### ISSUE THREAD

**Issue by russkel** [BruceSherwood/vpython-jupyter#35]
Currently I get errors in jupyter-lab when running the demo notebook script cells:

    JavaScript output is disabled in JupyterLab

I believe this has to do with changes to how javascript is included and ran in jupyterlab.

Similar issue for another python library: https://github.com/bokeh/bokeh/issues/6700

**Comment by russkel** [comment]
Would love to, will see how the time situation is in the coming weeks :).

**Comment by mwcraig** [comment]
One additional comment here -- it will be  necessary (or at least a lot
easier) to put some of the javascript on npm. I can help with that (and the
broader migrate-to-JupyterLab issue)...the only hitch is when I'll have the
time :frown:

**Comment by BruceSherwood** [comment]
I might be mistaken, but I don't see a role for npm here. The JavaScript component (glowcomm.js) is a small piece of VPython 7 and meaningless apart from the Python context that sends data to it. Nor do I see how it would help to put the GlowScript library on npm. Say more, Matt?

**Comment by sspickle** [comment]
Hi Bruce,

So I’m poking around the jupyterlab contributor documentation and I find that jupyterlab extensions are expected to use npm to manage the installation and development setup. Here’s an example extension  (see the instructions for a development install):

https://github.com/jupyterlab/jupyterlab_xkcd

It seems the npm is just cooked into the jupyterlab DNA somehow.

I did use npm extensively in a course I taught this fall and it does have some nice features.

I hope to have some “extra” cycles during my spring break (March 12-16) during which I hope to have some time to dig into this.

-steve

**Comment by BruceSherwood** [comment]
Interesting. I hope that you and Matt and John will figure out jupyterlab, as I would much prefer continuing to work on the other pieces.

**Comment by mwcraig** [comment]
Sorry for the delay -- in a nutshell, what @sspickle said. The extension mechanism is very different in JupyterLab than in Jupyter, and it tries hard to pull all JavaScript from npm. 

I'm quite sure the current mechanism (copying files into an nbextension directory) will not work in JupyterHub. It may (or may not) be possible to inject javascript directly into the notebook at run time.

When JupyterLab detects a change in the javascript of extensions it rebuilds the whole bundle of javascript packages that are installed, which can take a few minutes (this got to be a running joke at a jupyter widgets workshop in January).

On the upside, packaging for npm is really easy....

**Comment by BruceSherwood** [comment]
Correct me if I'm wrong, but I think/hope I'm hearing that both Matt and
Steve are willing to try to make VPython work in JupyterLab?

Bruce

**Comment by mwcraig** [comment]
Yes...and hopefully once break is done I'll have more time 😀

**Comment by sspickle** [comment]
Yes, correct!

**Comment by ruthchabay** [comment]
Several of our physics majors will be ecstatic.  They've been asking for
this.

**Comment by mwcraig** [comment]
Along the way we may as well make the non-lab version work as a real notebook extension instead of copying files directly into a user directory. There are several places extensions can ben installed and it isn't clear to me that what we are doing now is right if, for example, one is using environments...

**Comment by BruceSherwood** [comment]
Matt, I don't understand. I assumed that John's original scheme copies JS libraries to nbextensions (which is indeed a user directory) because that's the only place a notebook can or will look for extensions. You seem to be saying that our JS libraries could be somewhere else??

**Comment by mwcraig** [comment]
Yep; `jupyter --paths` will give you a list of the places it will look. I believe the output of that will change if you are in an python (virtual or conda) environment in which jupyter is installed.

Their recommendation for the last 6 months or more has been to install in `--sys-prefix` (which does a per-environment install) instead of `--user`, I think because the latter can/will override the former, leading to painful confusion about what is going on in an environment.

**Comment by sunilkpai** [comment]
How is this project coming along? Looking forward to it working in jupyter lab! :)

**Comment by sspickle** [comment]
Now that the semester is coming to an end I hope to have some more time to work on this soon!

-steve

**Comment by mwcraig** [comment]
Good news -- I'm closing this because v 7.5.0 (coming very soon!) works in JupyterLab (thanks to the efforts of @jcoady)
