### ISSUE TITLE
Quad setup function sets 4th vertex object _v3 to None

### ISSUE THREAD

**Issue by russkel** [BruceSherwood/vpython-jupyter#43]
I have the following code:
```python
            pt1 = vertex(pos=nodes[nx * N + ny].pos, color=vector(random(), random(), random()))
            pt2 = vertex(pos=nodes[(nx + 1) * N + ny].pos, color=vector(random(), random(), random()))
            pt3 = vertex(pos=nodes[nx * N + ny + 1].pos, color=vector(random(), random(), random()))
            pt4 = vertex(pos=nodes[(nx + 1) * N + ny + 1].pos, color=vector(random(), random(), random()))
            nodes[nx * N + ny].fill = quad(vs=[pt1, pt2, pt4, pt3])
```
If I do ```nodes[nx * N + ny].fill.vs[3]``` it returns a None object. I debugged into the code and tried to find out why but I can't work it out. I also don't understand what is happening with the decrement/incrementTriangleCount code.

**Comment by BruceSherwood** [comment]
Many thanks for the report. The bug was a simple typo. Will be fixed with next release.

**Comment by russkel** [comment]
Thanks @BruceSherwood. Could you please explain what the idea behind the triangle count code? I noticed it fell over when I tried to set the vs attribute of a quad object. It gave an error saying the triangle count was already 0.

**Comment by BruceSherwood** [comment]
Here are the two typos that had to be changed in vpython.py:

# @v3.setter => @v3.setter

elif i == 4: self.v3 = val => elif i == 3: self.v3 = val

These mistakes led indirectly to irrelevant error messages.
