### ISSUE TITLE
add Cython to requirements.txt to restore MyBinder building

### ISSUE THREAD

**Issue by fomightez** [BruceSherwood/vpython-jupyter#54]
My fork of this wasn't building after recent updates to Binder/repo2docker. I added `Cython` to `requirements.txt` after it was pointed out by @minrk that, "It has a cython requirement to build, but it isn't listed as a dependency." In regards to that he also added, "It's a new behavior of repo2docker to run `pip install . ` if it finds a `setup.py`. That's probably the relevant change."

**Comment by mwcraig** [comment]
@fomightez -- thanks for reporting this! The binder badge on our README should work for you now, but please reopen this if it does not.
