### ISSUE TITLE
ujson is a new required dependency?

### ISSUE THREAD

**Issue by mwcraig** [BruceSherwood/vpython-jupyter#7]
In building the conda package for 0.3.5 I found I had to add `ujson` as a dependency to complete the build. That is fine, and I was about to open a PR to add it to the requirements in setup.py, but am not sure what the intention is regarding `ujson` given this code: https://github.com/BruceSherwood/vpython-jupyter/blob/master/vpython/vpython.py#L29-L33

Given the `try/except` block I gather `ujson` should be an optional dependency, but there is an `import ujson` right before the `try/except`.

**Comment by BruceSherwood** [comment]
ujson was removed as a dependency, and the extraneous "import ujson" before the try block was removed.
