### ISSUE TITLE
Small values sent incorrectly

### ISSUE THREAD

**Issue by ruthchabay** [BruceSherwood/vpython-jupyter#9]
Using the most recent files from the repository, the following code fails.  The 7e-11 is received by glowcomm as 1e-10;  even smaller numbers are received as zero.

from vpython import *
gg = graph()
kk = gcurve(color=color.green)
kk.plot(0,0)
kk.plot(1e-9,7e-11)

**Comment by jcoady** [comment]
The ujson module had a default value of the number of significant digits to encode set to a value of 9. The number of significant digits has now been increased to 17 which is what the regular json module Is using. The fix for this has been committed to master.
